name: deploy to aliyun
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Person to greet"
        required: true
        default: "Owner"
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
          cache: "pnpm"
      - name: run pnpm install && build
        run: |
          pnpm install
          npm run build
      - name: ssh-deploy-XJP
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          REMOTE_PORT: ${{ secrets.XJP_REMOTE_PORT }}
          SSH_PRIVATE_KEY: ${{ secrets.XJP_SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.XJP_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.XJP_REMOTE_USER }}
          TARGET: ${{ secrets.XJP_TARGET }}
          SCRIPT_BEFORE: ls
      - name: ssh-deploy-HZ
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          REMOTE_PORT: ${{ secrets.HZ_REMOTE_PORT }}
          SSH_PRIVATE_KEY: ${{ secrets.HZ_SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.HZ_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.HZ_REMOTE_USER }}
          TARGET: ${{ secrets.HZ_TARGET }}
          SCRIPT_BEFORE: ls
